## Reference: https://engineering.ucsb.edu/~shell/che210d/numpy.pdf

In [1]:
import numpy as np

In [2]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [3]:
 a[:2]

array([1., 4.])

In [4]:
a[3]

8.0

In [5]:
a[0] = 2
a

array([2., 4., 5., 8.])

### Arrays

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
a[0,1]

2.0

Array slicing works with multiple dimensions in the same way as usual, applying each slice
specification as a filter to a specified dimension. Use of a single ":" in a dimension indicates the
use of everything along that dimension:

In [10]:
a[1,:]

array([4., 5., 6.])

In [11]:
 a[:,2]

array([3., 6.])

In [12]:
a.shape

(2, 3)

In [14]:
a.dtype

dtype('float64')

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
len(a)

2

In [16]:
2 in a

True

In [17]:
0 in a

False

In [18]:
a = np.array(range(10), float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
a = a.reshape((5, 2))
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])